# Generated by Django 3.2.7 on 2021-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
